openapi: 3.0.0
info:
  title: demo app
  description: Demo for mapper and conful
  version: 1.0.0
servers:
  - url: '/demo'
paths:

  /test:
    get:
      tags:
        - test
      operationId: testing
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestDTO'
components:
  schemas:
    TestDTO:
      type: object
      properties:
        msg:
          type: string
